//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Face_Recognition.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Security.Claims;

    public partial class User
    {
        public int user_id { get; set; }
        [Required(ErrorMessage = "Enter Your Email!")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string username { get; set; }
        [Required(ErrorMessage = "Enter Password!")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required(ErrorMessage = "Enter Confirm-Password!")]
        [Display(Name = "Confirm-Password")]
        [DataType(DataType.Password)]
        [Compare("password")]
        public string conf_pass { get; set; }
        [Required(ErrorMessage = "Upload Photo Please")]
        [Display(Name = "Photo")]
        public string photo { get; set; }
        [Required(ErrorMessage = "Choose Student role")]
        [Display(Name = "Role")]
        public int role_id { get; set; }
    }
}
